#ifndef PHATINA_LAYOUT_CONFIG
#define PHATINA_LAYOUT_CONFIG

#undef  MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 10

#undef  MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED   3

#endif // PHATINA_LAYOUT_CONFIG
